services:
  db:
    image: mysql:latest
    container_name: flask_mysql
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - flask_network

  flask_app:
    build: .
    container_name: flask_app
    env_file:
      - .env
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 5000
      FLASK_ENV: development
      DB_USER: root
      DB_PASSWORD: your_root_password
      DB_NAME: ${DB_NAME}
      DB_HOST: db
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - flask_network

volumes:
  mysql_data:

networks:
  flask_network:
    driver: bridge
